### ISSUE TITLE
Proposition d'amélioration

### ISSUE THREAD

**Issue by Hachebourin** [ExtensiveAutomation/extensiveautomation#10]
Hello,

- Dans l'adapter SSL, dans client, fonction initSocketSsl, j'ai rajouté le paramètre ciphers lorsqu'on veut préciser quel cipher utiliser :

![exxc](https://user-images.githubusercontent.com/19730082/37958002-a075ae98-31af-11e8-810e-c929510e4028.png)

- Dans le test initEnvironment on ne peut pas boucler sur une instances précise pour chaque serveur :

Prenons deux serveurs avec deux instances SSH : { ADMIN : ... }, { PROD : ... } 
On peut boucler sur les deux instances SSH sur nos deux serveurs du coup le script s'exécutera sur ADMIN et PROD.
Cependant on ne peut pas préciser de boucler sur nos deux serveurs uniquement sur l'instance ADMIN ou PROD.

J'ai fait la modification sur notre script mais il ne ressemble pas tout à fait à la version dispo dans le initialize de la v18. Je peux essayer de retrouver le bout de code que j'ai rajouté mais ça fait longtemps. Et puis ça augmente un peu le temps d'initialisation.

Du coup j'avais pensé à rajouter un bool : if input('PREPARE_ENV'):
On set la variable PREPARE_ENV à false dans notre testplan et dans le test d'initialisation on crée un alias de PREPARE_ENV que l'on met à true pour qu'il soit initialiser qu'une fois. Ca fait gagner pas mal de temps lorsqu'il y a beaucoup de test. Par contre il ne faut pas reset le cache dans les tests suites ...

**Comment by dmachard** [comment]
c'est pris en compte pour la 1ière amélioration
pour le dernier point c'est une bonne idée :)

**Comment by dmachard** [comment]
le test pour préparer un environnement est considéré comme déprecated depuis la version 19.0
Il faut utiliser la nouvelle permettant de mettre en cache un paramètre directement depuis les paramètres.
