### ISSUE TITLE
Fonction getSize introuvable => adapter http

### ISSUE THREAD

**Issue by Hachebourin** [ExtensiveAutomation/extensiveautomation#13]
La fonction getSize dans l’adapter http (server) n’existe pas :

![37956363-73ea5dc8-31ab-11e8-82c2-798f275a2450](https://user-images.githubusercontent.com/19730082/38053225-d0edd54e-32d3-11e8-9101-ed1a78b9e4f0.png)

J'ai dû la commenter pour exécuter les tests.

**Comment by dmachard** [comment]
Est-ce que par hasard tu aurais un fichier TestTemplateLib.py qui contient une fonction "getSize" sur tes différents serveur ? Je pense qu'un bout se code à du se perdre avant l'utilisation de github..

**Comment by Hachebourin** [comment]
Aucun fichier TestTemplateLib.py ...

J'ai juste trouvé une fonction getSize dans Core/Context.py mais elle est présente sur toutes les versions XTC.

**Comment by dmachard** [comment]
corrigé dans la version 19.0
