### ISSUE TITLE
Error executing test plan with REST interface

### ISSUE THREAD

**Issue by danieldds1983** [ExtensiveAutomation/extensiveautomation#21]
Utilisant l’interface REST pour exécuter un test plan avec l’URL : http://.../rest/tests/schedule/tpg et avec test inputs conduit à une erreur : « "error": "Internal server error encountered." »

Le body du request :

{
                           "test-path": "/Tests/Accessibilite",
                           "test-name": "[AUT] Test Connection Juniper EX3300 Haut",
                           "test-extension": "tpx",
                           "project-id": 2,
                           "schedule-id": 0,
                           "test-inputs": [
                                 {"name": "QC_TESTSET_PATH" , "type": "str", "value": "testSetPath"},
                                 {"name": "QC_TESTSET_NAME" , "type": "str", "value": "CurrentTestSet"},
                                 {"name": "QC_INSTANCE_NAME" , "type": "str", "value": "instanceName"},
                                 {"name": "QC_WRITE_RESULT" , "type": "bool", "value": "False"}
                                 ]
}

Sans le champ « test-inputs » la exécution ça fonctionne. Avec le champ je vois dans le server log :

'scope'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pycnic/core.py", line 204, in __iter__
    resp = self.delegate()
  File "/usr/local/lib/python2.7/site-packages/pycnic/core.py", line 269, in delegate
    output = func(*args)
  File "/opt/xtc/ExtensiveAutomation-19.0.1/ServerControls/RestTesterFunctions.py", line 54, in _to_yaml
    return wrapped(*args, **kwargs)
  File "/opt/xtc/ExtensiveAutomation-19.0.1/ServerControls/RestTesterFunctions.py", line 6158, in post
    origInp["scope"] = newInp["scope"]
KeyError: 'scope'

**Comment by dmachard** [comment]
fix in next release
