### ISSUE TITLE
Unable to build test designs in version 19

### ISSUE THREAD

**Issue by eagle842** [ExtensiveAutomation/extensiveautomation#22]
### description of the issue

In the client, when trying launch a design of a test after opening it, I get the error message :

Unable to prepare the design of the test!
Syntax error detected in this test!

The design after test execution works though.

### steps to reproduce the issue

1. Open a test unit/suite/plan
2. Click on the "Design" button.

### additionnals informations like versions, logs, screenshots
![image](https://user-images.githubusercontent.com/33343422/51029874-ece22780-1597-11e9-8e2d-cdfaef24d91b.png)

**Comment by dmachard** [comment]
fix in next release
